# title (the comment helps)
title: "Re-Equation"

# theming
remote_theme: pmarsceill/just-the-docs
color_scheme: dark

#the links in the top right of the page
aux_links:
  "Github":
    - "https://github.com/mckahz/re-equation"

# navigation
collections:
  geometry:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    geometry:
      name: Geometry
      nav_exclude: false
      search_exclude: false