# title (the comment helps)
title: "Maths Is Useless"

# theming
remote_theme: "pmarsceill/just-the-docs"
color_scheme: dark

#the links in the top right of the page
aux_links:
  "Github":
    - "https://github.com/mckahz/re-equation"